### ISSUE TITLE
ShallowRecordFinder ignores translations for rootRecord

### ISSUE THREAD

**Issue by YKWeyer** [in2code-de/in2publish_core#107]
`ShallowRecordFinder::findPageRecord` doesn't seem to fetch translations of the rootRecord. The required logic is provided in `ShallowRecordFinder::addChildPagesRecursively`, making it possible to view (and publish) translations of child records, but not for the root record.

(Reproduced with TYPO3 v11.5, in2publish_core v11.0.8)

I will provide a simple workaround based on the logic already used, but you might have better ideas on how to fix it.

**Comment by vertexvaar** [comment]
**For anyone**: The development of the 11.x branch has been discontinued in favor of the 12.x branch.
CP v12 is much faster and uses less resources. It supports the same TYPO3 and PHP version as v11 and can be upgraded in-place. If doing so, please read the UPGRADING.md documentation.

@YKWeyer I assume this issue is not relevant for you anymore as you upgraded to v12 already. Therefore I am closing this issue and the associated PR. If you still require this change you can reopen this issue.
