### ISSUE TITLE
Could not execute RPC [828]

### ISSUE THREAD

**Issue by bergisch-media** [in2code-de/in2publish_core#11]
Hi, 

We are using the latest versions of in2publish_core and in2publish.

Our TYPO3 system log lists the following exception:

`Could not execute RPC [828]. An error occurred on foreign: Oops, an error occurred: PHP Warning: unlink(PATH_TO_FILE_IN_FILEADMIN.mp4): No such file or directory in PATH/typo3/sysext/core/Classes/Resource/Driver/LocalDriver.php line 1177 | RuntimeException thrown in file PATH/typo3conf/ext/in2publish_core/Classes/Domain/Driver/RemoteFileAbstractionLayerDriver.php in line 696. Requested URL: URL/typo3/index.php?M=web_In2publishM2&moduleToken=926559963c5e0f7e31a74a0eb485cfcd67570578&id=88&tx_in2publish_web_in2publishm2%5Bidentifier%5D=729&tx_in2publish_web_in2publishm2%5BtableName%5D=tx_bmnews_domain_model_basenews&tx_in2publish_web_in2publishm2%5Baction%5D=publishSingleRecord&tx_in2publish_web_in2publishm2%5Bcontroller%5D=Workflow `

It's a record table with custom worklfow.

**Comment by vertexvaar** [comment]
Hi,

unfortunately i can not tell you what to do to solve this issue, because it could have a million reasons in the code.
What the Exception tells me is: You published "tx_bmnews_domain_model_basenews" [729] via SRP and it has at least one relation to a file which did not exist on local or the record was deleted. The file on foreign did not exist when the publishing process began.

If you could tell me about the state of the record on local and foreign before and after it was published, as well as on which side a file existed i might figure out some more.

**Comment by vertexvaar** [comment]
Hi @bergisch-media,

it has been a while since your last response. Because this issue is missing a reply for over a month i will close this, because it seems to be not important or fixed. If you still experience this issue please open another ticket with a full explanation and the missing details.
