### ISSUE TITLE
Allow manuel disabling of RealUrl Task

### ISSUE THREAD

**Issue by ohartwig** [in2code-de/in2publish_core#21]
Please add one configuration option to disable the RealUrl-Task in the configuration so that the Task is not exclude even if RealUrl is installed.

**Comment by vertexvaar** [comment]
Hi @ohartwig 

can you explain why this should be possible? For me it's rather a source of error than a useful feature. Can you provide an actual use case?

**Comment by ohartwig** [comment]
Hey @vertexvaar
if you use an alternate RealUrl Version like https://github.com/helhum/realurl the check if realurl is installed returns an false positive result. In this case the RealUrl Hook can not execute and the publishing fails.

**Comment by vertexvaar** [comment]
Hi @ohartwig,

Helmuts fork does the exact same as Dmitrys original RealUrl, is fully backwards compatible and is also aimed at installations lower than 7.6. Other than that the original RealUrl extension is available at packagist as well and one does well require the original one for the sake of security, performance and features.
Since the new LTS version TYPO3 v8.7 was released we dropped support for 6.2 (We support both LTS versions, which are 7.6 and 8.7 at this time). Therefore there is no need to run the forked version, because there are no benefits anymore.
Please consider changing to the original RealUrl, the deactivation of the RealUrl-Tasks will result in weird caches and even Exceptions, if RealUrl-Caches of e.g. moved (and/or deleted) pages are not properly cleared.

**Comment by ohartwig** [comment]
Hi @vertexvaar 
the latest RealUrl Version from Dmitry has not the same Featureset as the old RealUrl, so we have at this time no option to update RealUrl.

**Comment by vertexvaar** [comment]
We always try to find the best solution for every user of this extension, which is why we only implement features that are beneficial for the biggest part of the installed base.
We are eager to fully support any feature that comes with a default TYPO3, which does not include any other Extension. That is simply not possible, as there are over 1790 Extensions. But we support RealUrl by choice and out of the box, which is one of the biggest benefits for most of the users. Helmuts RealUrl is a fork of RealUrl, which is not supported in terms of conflict avoidance because it is another extension, but a fork in addition.

Since you told me in Slack that you will implement this feature by yourself i'm going close this issue.
