### ISSUE TITLE
RCE API not used for FilePublisherService::transferTemporaryFile()

### ISSUE THREAD

**Issue by AndreasA** [in2code-de/in2publish_core#24]
FilePublisherService::transferTemporaryFile() still uses SshConnection and not the new RCE API.

Also: RemoteStorage still creates a SshConnection instance which isn't used.

**Comment by vertexvaar** [comment]
Hey @AndreasA 

it's awesome that you had such an deep look into the code. The RCE API is however not meant to transfer files. Its solely purpose is to execute commands on the CLI. I did this separation on purpose, because the RCE API is used in an early state and must not rely on the createMasks as SshConnection did. This also helps to prevent unrelated errors.
 There is currently not replacement for `SshConnection::transferTemporaryFile` because i did not come up with a full concept (which should also be bullet proof) on how to replace it with a better implementation. Therefore it's still used, as it has been and is still working (kind of 😄 ).

Concerning SshConnection and the RemoteStorage: Thank you for the hint, i removed it.

**Comment by AndreasA** [comment]
OK. However, SshConnection doesn't "sanitize" the SSH response.
