### ISSUE TITLE
[BUG] Preview doesn't work with "Include before all static templates if root flag is set" template option

### ISSUE THREAD

**Issue by AndreasA** [in2code-de/in2publish_core#31]
If one uses the template option then the assignment of 
"10 < tt_content.list.20.in2publishcore_pi1" for the preview won't work.

The reason is that the plugin will be added afterwards.
Two solutions:
1.) Execute the Plugin directly via the TYPO3 extbase bootstrap class
2.) Assign the information by reference that way it should also work if the list plugin is defined later.
3.) add the TypoScript in ext_localconf.php after configuring the plugin by using the ExtensionManagementUtility

I think the first solution would be the best.

**Comment by vertexvaar** [comment]
I've chosen your second proposal, because we must still configure the plugin via ExtensionUtility and we can use the registered TypoScript from over there and be more upwards compatible (despite the extbase plugin registration is unlikely to change in the next few years). Also, changing parts of the plugin registration does not result in two files changed but one.
