### ISSUE TITLE
[QUESTION] Should realurl tables like tx_realurl_urldata be added to excludeRelatedTables?

### ISSUE THREAD

**Issue by AndreasA** [in2code-de/in2publish_core#38]
Should the realurl tables be added to excludeRelatedTables?

The new ones have uid / pid and also TCA, so in2publish would recodnize them when accessing the page 0 but I guess they should be removed from transfer which would be these tables:
  - tx_realurl_uniqalias
  - tx_realurl_uniqalias_cache_map
  - tx_realurl_urldata
  - tx_realurl_pathdata

Or should one or multiple of them be part of the publish process?

**Comment by vertexvaar** [comment]
tl;dr: Yes.

RealUrl entries are managed by RealUrl itself (via publishing tasks) and they should not get published, so it's both safe and good to add these tables to `excludeRelatedTables`.

Before you ask: They are not in the default list, because RealUrl is not part of a default TYPO3 installation. The config section therefore would be invalid.

**Comment by AndreasA** [comment]
Thanks for the answer. 
I actually didn't wonder why they are not part of the default configuration because as you mentioned realurl is not part of the default TYPO3 installation.
But I also couldn't find any entry regarding this in the documentation, so I thought I better ask before doing anything stupid.
However, it just made more sense to add those tables to `excludeRelatedTables`
