### ISSUE TITLE
Exception when opening the File-Module of in2publish_core

### ISSUE THREAD

**Issue by einpraegsam** [in2code-de/in2publish_core#7]
Opening the backend module on my local machine results in an exception.
Tests are green, Install tool suggest no relevant changes in db if I click on db-compare.

<img src="https://box.everhelper.me/attachment/715725/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-FEMlgJl7mVKLLibQ/screen.png" />

**Comment by vertexvaar** [comment]
It is, in fact, an escaping issue in the SQL statement, but nevertheless you really shouldn't use dots in database names since they are not allowed for unquoted identifiers: http://dev.mysql.com/doc/refman/5.7/en/identifiers.html
This bug will most likely not occur "in the wild" but i will fix it before the next release.
